version: "3"

services:
  react-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-portfolio
    entrypoint: sh setup.sh
    working_dir: /home/node
    ports:
      - 3000:3000
    volumes:
      - .:/home/node